name: deploy

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js v14.x
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Install
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy
        # uses: peaceiris/actions-gh-pages@v3
        user: JamesIves/github-pages-deploy-action@4
        with:
          publish_dir: ./dist
          github_token: ${{ secrets.ACCESS_TOKEN }}
          user_name: ${{ secrets.ACCESS_USER_NAME }}
          user_email: ${{ secrets.ACCESS_USER_EMAIL }}
          repository-name: 474288926/474288926.github.io #github page 仓库
          target-folder: github-actions-docs
          commit_message: Update Vite2.x + Vue3.x + TypeScript Starter
